"""
Aegis → Linear Integration
Creates 'Defensive Strategy' tickets via the Linear GraphQL API.
Falls back to mock URLs when LINEAR_API_KEY is not configured.
"""
import os
import json
import requests
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), '.env'))

LINEAR_API_URL = os.getenv("LINEAR_API_URL", "https://api.linear.app/graphql")
LINEAR_API_KEY = os.getenv("LINEAR_API_KEY", "")
LINEAR_TEAM_ID = os.getenv("LINEAR_TEAM_ID", "")

MOCK_TICKET_URL = "https://linear.app/aegis/issue/AEG-1042/defensive-strategy-competitive-response"


def create_defensive_strategy_ticket(
    strategy: str,
    arr_risk: str,
    drift_score: float,
    signals_captured: int = 7,
) -> dict:
    """
    Create a Defensive Strategy ticket in Linear.

    Returns:
        dict with 'url', 'identifier', and 'title' keys.
    """
    title = f"[AEGIS] Defensive Strategy — Drift {drift_score}/100"
    description = (
        f"## Strategic Pivot Required\n\n"
        f"**ARR at Risk:** {arr_risk}\n"
        f"**Strategic Drift Score:** {drift_score}/100\n"
        f"**Signals Captured:** {signals_captured}\n\n"
        f"### Recommended Strategy\n{strategy}\n\n"
        f"### Context\n"
        f"This ticket was auto-generated by the Aegis War Room after a multi-agent "
        f"debate between the Optimist and Skeptic agents reached consensus.\n\n"
        f"**Priority:** Urgent\n"
        f"**Label:** Strategic Pivot"
    )

    if not LINEAR_API_KEY or not LINEAR_TEAM_ID:
        # Sandbox fallback
        return {
            "url": MOCK_TICKET_URL,
            "identifier": "AEG-1042",
            "title": title,
            "mock": True,
        }

    mutation = """
    mutation CreateIssue($title: String!, $description: String!, $teamId: String!) {
        issueCreate(input: {
            title: $title,
            description: $description,
            teamId: $teamId,
            priority: 1
        }) {
            success
            issue {
                id
                identifier
                url
                title
            }
        }
    }
    """

    headers = {
        "Authorization": LINEAR_API_KEY,
        "Content-Type": "application/json",
    }

    payload = {
        "query": mutation,
        "variables": {
            "title": title,
            "description": description,
            "teamId": LINEAR_TEAM_ID,
        },
    }

    try:
        resp = requests.post(LINEAR_API_URL, headers=headers, json=payload, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        if "errors" in data:
            print(f"Linear GraphQL Error: {json.dumps(data['errors'], indent=2)}")
        issue = data.get("data", {}).get("issueCreate", {}).get("issue", {})
        return {
            "url": issue.get("url", MOCK_TICKET_URL),
            "identifier": issue.get("identifier", "AEG-???"),
            "title": issue.get("title", title),
            "mock": False,
        }
    except Exception as e:
        return {
            "url": MOCK_TICKET_URL,
            "identifier": "AEG-1042",
            "title": title,
            "mock": True,
            "error": str(e),
        }

if __name__ == "__main__":
    print(f"DEBUG: LINEAR_API_KEY starts with: {LINEAR_API_KEY[:10] if LINEAR_API_KEY else 'NONE'}")
    print(f"DEBUG: LINEAR_TEAM_ID: {LINEAR_TEAM_ID if LINEAR_TEAM_ID else 'NONE'}")
    res = create_defensive_strategy_ticket("Consensus reached: Pivot to defensive engagement in North America.", "$415k", 72.5)
    print(f"Linear Ticket Status: {'Live' if not res.get('mock') else 'Mock'}")
    if res.get('mock') and res.get('error'):
        print(f"Linear Error: {res.get('error')}")
    print(f"URL: {res.get('url')}")
